server:
  port: 8081

spring:
  application:
    name: springboot-grpc-client

grpc:
  client:
    springboot-grpc-server:
      # 如果你没有使用docker-compose方式启动Demo，则需要将此处host改为对应IP地址
      host:
         - 127.0.0.1
        #-0.0.0.0
        #- springboot-grpc-server
      port:
        - 20820
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

